### ISSUE TITLE
How to add multiple matrices in dvarlag()?

### ISSUE THREAD

**Issue by chen5349** [JanDitzen/nwxtregress#12]
Dear Jan,

It seems that multiple matrices could not be added to dvarlag(), but only multiple matrices in ivarlag(). See if you could post the solution to it.
Thank you very much!

Best,
Wenna

**Comment by JanDitzen** [comment]
Hi Wenna,
do you have some code example.

In general it is only possible to use one spatial lag for the dependent variable, not multiple.

Thanks!
Jan

**Comment by chen5349** [comment]
Thank you for the response, Jan.

My coding is as follow: 
`nwxtregress ln_gdp industry_2nd income   YEAR1-YEAR4 ,dvarlag(Wnetwork, mata timesparse) ivarlag(Wnetwork:industry_2nd, mata timesparse)  ivarlag(Wnetwork2:income, mata timesparse)  seed(1234) 
`

Wenna

**Comment by JanDitzen** [comment]
Hi Wenna,
the code example should work with the latest version. Two weight matrices for independent variables can be used.
Jan
