### ISSUE TITLE
Questions when run nwxtregress

### ISSUE THREAD

**Issue by Edwardlee20** [JanDitzen/nwxtregress#13]
nwxtregress cap_cons compensation net_surplus , dvarlag(WSpmat) seed(1234)
error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
(43 lines skipped)

when I run this code, I met this error.

**Comment by JanDitzen** [comment]
Which Stata version do you use? It looks like nwxtregress is trying to use Python, but fails.
