### ISSUE TITLE
r(199); reghdfe Mata library not found or error in reghdfe.

### ISSUE THREAD

**Issue by AaronPengDing** [JanDitzen/nwxtregress#18]
Dear Jan, 
I run the demo code in your GitHub:

Partial out firm and year fixed effects (requires reghdfe):
nwxtregress cap_cons compensation net_surplus , dvarlag(Wt,mata timesparse) ivarlag(Wt: compensation,mata timesparse )  seed(1234) absorb(ID Year)

I encounter the following error message:
reghdfe Mata library not found or error in reghdfe.
r(199);

I use stata 17MP and update the reghdfe.
Thank you!
Peng

**Comment by JanDitzen** [comment]
Hi Peng,
thank you very much for your question. This seems to be an error with reghdfe. What happens if you type:
`reghdfe, version`
respectively
`nwxtregress cap_cons compensation net_surplus , dvarlag(Wt,mata timesparse) ivarlag(Wt: compensation,mata timesparse ) seed(1234) absorb(ID Year, trace)`

**Comment by AaronPengDing** [comment]
Thank you, Jan.
When I type:
. reghdfe, version
last estimates not found
r(301);

. nwxtregress cap_cons compensation net_surplus , dvarlag(Wt,mata timesparse) ivarlag(Wt: compensation,mat
> a timesparse ) seed(1234) absorb(ID Year, trace)


command reghdfe_parse is unrecognized
                 stata():  3598  Stata returned error
         fixed_effects():     -  function returned error
                 <istmt>:     -  function returned error
reghdfe Mata library not found or error in reghdfe.
r(199);

and this is the version of reghdfe
. which reghdfe
C:\Stata17\ado\plus\r\reghdfe.ado
*! version 6.12.2 02Nov2021

**Comment by JanDitzen** [comment]
Thanks. I think there is a bug in reghdfe in the latest version from GitHub. Can you please try the version from SSC?

**Comment by AaronPengDing** [comment]
I install the stable version of reghdfe from SSC, and now it works.
Thank you!

**Comment by JanDitzen** [comment]
Thanks for letting me know. I will add a note for future versions.
Cheers

**Comment by Thomasccc113** [comment]
I have same problem.
I install the version of reghdfe from SSC, but it can't work.
when put in which reghdfe,and it display D:\new_stata17\ado\base\r\reghdfe.ado
*! version 6.12.3 08aug2023.please help me.thank you so very much!!!!

**Comment by JanDitzen** [comment]
Do you get the same error as the one above or a different one?

**Comment by Thomasccc113** [comment]
> Do you get the same error as the one above or a different one?

yes，i get the same error,which is "reghdfe Mata library not found or error in reghdfe"

**Comment by JanDitzen** [comment]
Can you run reghdfe without any problems?

Can you also try to first remove reghdfe and then reinstall it? My version is 6.12.5 which works with nwxtregress.

**Comment by Thomasccc113** [comment]
I first tried running reghdfe, and it worked. Then I reinstalled version 6.12.5 of the reghdfe command. 
later, I realized I had put in the wrong time variable name. 
and I fixed it, the problem was solved. 
Sorry for the careless mistake, and thank you for your patient help.
