### ISSUE TITLE
Regression Error: This is an alpha version! Results may change. 

### ISSUE THREAD

**Issue by ZhihaoMa** [JanDitzen/nwxtregress#3]
When I run the example regression, Stata shows "This is an alpha version! Results may change. ". 

System: Windows 10
Stata Version: 15.0

**Comment by JanDitzen** [comment]
Thank you very much for your interest in nwxtregress.

The current version is an alpha version and therefore results may change. 

The message is an intended reminder for the user that this is the case and to check results with the latest version prior to publishing.

**Comment by ZhihaoMa** [comment]
Thanks for your responses.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
21/08/24
下午02:12:32

Jan Ditzen ***@***.***> 于2021年8月24日周二 下午2:11写道：
