### ISSUE TITLE
Bug report in running -nwxtregress-

### ISSUE THREAD

**Issue by bruce4research** [JanDitzen/nwxtregress#7]
Hi,
When I run `nwxtregress cap_cons compensation net_surplus , dvarlag(WSpmat) seed(1234)` following the codes in help page, the error information is as follows:
'''
Initialise Grid (200)   
----+--- 10 --+--- 20 --+--- 30 --+--- 40 --+--- 50   %  
..................................................   50  
..................................................  100  
Griddy Gibbs (2000)   
----+--- 10 --+--- 20 --+--- 30 --+--- 40 --+--- 50   %  
          mm_colrunsum():  3001  expected 1 arguments but received 3  
          GriddyGibbsi():     -  function returned error  
           GriddyGibbs():     -  function returned error  
           estimatesar():     -  function returned error  
                 <istmt>:     -  function returned error  
r(3001);
'''
My Stata is SE 17.0 for Windows.

Thanks and best wishes.

**Comment by JanDitzen** [comment]
Hi @bruce4research ,
thank you very much for your interest in nwxtregress.

The error is caused by the moremata packaged. Can you please update moremata to the latest version and restart Stata. 

Please let us know if that helps.

Best,

Jan

**Comment by bruce4research** [comment]
Thanks for your advice. It's very helpful.
`ssc install moremata, replace`  My problem is solved. 
Thanks again.
