### ISSUE TITLE
an issue of estat imapct after nwxtregress estimation

### ISSUE THREAD

**Issue by suhchc** [JanDitzen/nwxtregress#8]
Hello, 
while trying to use estat imapct after successfully run nwxtregress, Stata gives the following error message, wondering if it is a bug. 

. estat impact
----+--- 10 --+--- 20 --+--- 30 --+--- 40 --+--- 50   %
                     J():  3900  unable to allocate real <tmp>[2147379216,50]
        SparseMultiply():     -  function returned error
             BarryPace():     -  function returned error
        calc_DIEffects():     -  function returned error
                 <istmt>:     -  function returned error
r(3900);

Stata 16.1

**Comment by JanDitzen** [comment]
Hi,
I think the problem might be the dimensions of your data and that mata cannot create a large enough matrix. How many cross-sectional units and time periods do you have?

**Comment by suhchc** [comment]
Hello Dr. Ditzen,

The relationship data is a cross sectional dataset with 3656 relationship pairs, one time period.  I attached the relationship dataset if it helps. The cross-sectional number of units in the main analysis is 5298, also one time period.
Thank you.

-HCSU

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
寄件者: Jan Ditzen ***@***.***>
寄件日期: Thursday, December 9, 2021 2:01:33 AM
收件者: JanDitzen/nwxtregress ***@***.***>
副本: suhchc ***@***.***>; Author ***@***.***>
主旨: Re: [JanDitzen/nwxtregress] an issue of estat imapct after nwxtregress estimation (Issue #8)


Hi,
I think the problem might be the dimensions of your data and that mata cannot create a large enough matrix. How many cross-sectional units and time periods do you have?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJanDitzen%2Fnwxtregress%2Fissues%2F8%23issuecomment-989570456&data=04%7C01%7C%7C8541e8a750ea49ac281f08d9bae1bc85%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746300963940823%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GxKoSbMDBd0oPbiy%2BArZAAXLnNVX91AzV6sbn2LFP6s%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW2UPCRQ6QIRSDEHIBC3F63UQBH43ANCNFSM5JUF7YPQ&data=04%7C01%7C%7C8541e8a750ea49ac281f08d9bae1bc85%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746300963940823%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=clmdLjo%2FHh%2BcAMzoYQP7pTKKjEPDBYgWtpz4kRygqdg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C8541e8a750ea49ac281f08d9bae1bc85%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746300963940823%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FPCXUFQO7z6l4LhGVX1n12%2FiJX6eTJnrY%2F5gDFwDzIA%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C8541e8a750ea49ac281f08d9bae1bc85%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637746300964097050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XetoHVuFZNLXcG1b1tXbt5QAwkcDZxEBcL95MfXdHiY%3D&reserved=0>.

**Comment by JanDitzen** [comment]
Thanks for your answer. Can you please provide me with the exact command line you are using.
Thanks.

**Comment by suhchc** [comment]
frame create relation
frame change relation
use  "proj_relation.dta"
putmata Wt = (year project_pid1 project_pid2 num), replace

frame change default
use “project.dta”

nwxtregress final_pledged_in_usd backers_count faq_count img_count video_count rewards_count title_length blurb_length description_length most_recent_comments_count most_recent_updates_count ,dvarlag(Wt, mata timesparse) seed(1234)

estat impact //with error msg

. estat impact
----+--- 10 --+--- 20 --+--- 30 --+--- 40 --+--- 50   %
                     J():  3900  unable to allocate real <tmp>[2147379216,50]
        SparseMultiply():     -  function returned error
             BarryPace():     -  function returned error
        calc_DIEffects():     -  function returned error
                 <istmt>:     -  function returned error
r(3900);

Thanks for your help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by JanDitzen** [comment]
Can you please check if the issue persists with the latest version. Thanks! Jan
